### ISSUE TITLE
`./gradlew build` was failed because of different checksum for gradle.

### ISSUE THREAD

**Issue by togatoga** [msfroh/lucene-university#8]
I run `./gradlew build` and got an error at 723319288691cac9ebc4f2ff793aac96876894b7.

```bash
% ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-8.5-bin.zip
............10%.............20%............30%.............40%.............50%............60%.............70%.............80%............90%.............100%
Exception in thread "main" java.lang.RuntimeException: Verification of Gradle distribution failed!

Your Gradle distribution may have been tampered with.
Confirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.

 Distribution Url: https://services.gradle.org/distributions/gradle-8.5-bin.zip
Download Location: /Users/togatoga/.gradle/wrapper/dists/gradle-8.5-bin/5t9huq95ubn472n8rpzujfbqh/gradle-8.5-bin.zip
Expected checksum: 'c16d517b50dd28b3f5838f0e844b7520b8f1eb610f2f29de7e4e04a1b7c9c79b'
  Actual checksum: '9d926787066a081739e8200858338b4a69e837c3a821a33aca9db09dd4a41026'

        at org.gradle.wrapper.Install.verifyDownloadChecksum(Install.java:244)
        at org.gradle.wrapper.Install.fetchDistribution(Install.java:109)
        at org.gradle.wrapper.Install.access$400(Install.java:46)
        at org.gradle.wrapper.Install$1.call(Install.java:81)
        at org.gradle.wrapper.Install$1.call(Install.java:68)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:68)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:102)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:66)
[main][togatoga] ~/src/github.com/msfroh/lucene-university
```

I succeeded in building this command when I changed the head to 9c2b509196699665ed67eca779246e176c654439.

**Comment by msfroh** [comment]
Thank you for the fix!
